apiVersion: v1
kind: Pod
metadata:
  name: sample3
spec:
    containers:
      - name: nginx
        image: nginx
        env:
          - name: URL
            value: google.com

---
apiVersiom: v1
kind: ConfigMap
metadata:
    name: config1
data:
   URL: sample.com
   URL1: yahoo.com
---
apiVersion: v1
kind: Pod
metadata:
  name: sample4
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - ConfigMapRef:
            name: config1