apiVersion: v1
kind: Pod
metadata:
   name: sample5
spec:
    containers:
         - name: health
           image: vasubandaru/health-demo:latest
           imagePullPolicy: Always
           readinessProbe:
              httpGet:
                 path: /
                 port: 80
              initialDelaySeconds: 5
              periodSeconds: 10
           livenessProbe:
              httpGet:
                  path: /
                  port: 80
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
                         httpGet:
                             path: /
                             port: 80
                         initialDelaySeconds: 5
                         periodSeconds: 10