apiVersion: v1
kind: Pod
metadata:
   name: sample5
spec:
    containers:
         - name: health
           image: vasubandaru/health-demo:latest
           imagePullPolicy: Always
           readinessProbe:
              tcpSocket:
                  port: 80
              initialDelaySeconds: 5
              periodSeconds: 10
           livenessProbe:
              tcpSocket:
                  port: 80
              initialDelaySeconds: 5
              periodSeconds: 10